while True:
    x = int(input("Input a number: "))
    x = abs(x)
    if x == 0:
        print('The number is even')
    elif x == 1:
        print('The number is odd')
    elif x == 2:
        print('The number is even')
    elif x == 3:
        print('The number is odd')
    elif x == 4:
        print('The number is even')
    elif x == 5:
        print('The number is odd')
    elif x == 6:
        print('The number is even')
    elif x == 7:
        print('The number is odd')
    elif x == 8:
        print('The number is even')
    elif x == 9:
        print('The number is odd')
    elif x == 10:
        print('The number is even')
    elif x == 11:
        print('The number is odd')
    elif x == 12:
        print('The number is even')
    elif x == 13:
        print('The number is odd')
    elif x == 14:
        print('The number is even')
    elif x == 15:
        print('The number is odd')
    elif x == 16:
        print('The number is even')
    elif x == 17:
        print('The number is odd')
    elif x == 18:
        print('The number is even')
    elif x == 19:
        print('The number is odd')
    elif x == 20:
        print('The number is even')
    elif x == 21:
        print('The number is odd')
    elif x == 22:
        print('The number is even')
    elif x == 23:
        print('The number is odd')
    elif x == 24:
        print('The number is even')
    elif x == 25:
        print('The number is odd')
    elif x == 26:
        print('The number is even')
    elif x == 27:
        print('The number is odd')
    elif x == 28:
        print('The number is even')
    elif x == 29:
        print('The number is odd')
    elif x == 30:
        print('The number is even')
    elif x == 31:
        print('The number is odd')
    elif x == 32:
        print('The number is even')
    elif x == 33:
        print('The number is odd')
    elif x == 34:
        print('The number is even')
    elif x == 35:
        print('The number is odd')
    elif x == 36:
        print('The number is even')
    elif x == 37:
        print('The number is odd')
    elif x == 38:
        print('The number is even')
    elif x == 39:
        print('The number is odd')
    elif x == 40:
        print('The number is even')
    elif x == 41:
        print('The number is odd')
    elif x == 42:
        print('The number is even')
    elif x == 43:
        print('The number is odd')
    elif x == 44:
        print('The number is even')
    elif x == 45:
        print('The number is odd')
    elif x == 46:
        print('The number is even')
    elif x == 47:
        print('The number is odd')
    elif x == 48:
        print('The number is even')
    elif x == 49:
        print('The number is odd')
    elif x == 50:
        print('The number is even')
    elif x == 51:
        print('The number is odd')
    elif x == 52:
        print('The number is even')
    elif x == 53:
        print('The number is odd')
    elif x == 54:
        print('The number is even')
    elif x == 55:
        print('The number is odd')
    elif x == 56:
        print('The number is even')
    elif x == 57:
        print('The number is odd')
    elif x == 58:
        print('The number is even')
    elif x == 59:
        print('The number is odd')
    elif x == 60:
        print('The number is even')
    elif x == 61:
        print('The number is odd')
    elif x == 62:
        print('The number is even')
    elif x == 63:
        print('The number is odd')
    elif x == 64:
        print('The number is even')
    elif x == 65:
        print('The number is odd')
    elif x == 66:
        print('The number is even')
    elif x == 67:
        print('The number is unholy.')
    elif x == 68:
        print('The number is even')
    elif x == 69:
        print('The number is funny :)')
    elif x == 70:
        print('The number is even')
    elif x == 71:
        print('The number is odd')
    elif x == 72:
        print('The number is even')
    elif x == 73:
        print('The number is odd')
    elif x == 74:
        print('The number is even')
    elif x == 75:
        print('The number is odd')
    elif x == 76:
        print('The number is even')
    elif x == 77:
        print('The number is odd')
    elif x == 78:
        print('The number is even')
    elif x == 79:
        print('The number is odd')
    elif x == 80:
        print('The number is even')
    elif x == 81:
        print('The number is odd')
    elif x == 82:
        print('The number is even')
    elif x == 83:
        print('The number is odd')
    elif x == 84:
        print('The number is even')
    elif x == 85:
        print('The number is odd')
    elif x == 86:
        print('The number is even')
    elif x == 87:
        print('The number is odd')
    elif x == 88:
        print('The number is even')
    elif x == 89:
        print('The number is odd')
    elif x == 90:
        print('The number is even')
    elif x == 91:
        print('The number is odd')
    elif x == 92:
        print('The number is even')
    elif x == 93:
        print('The number is odd')
    elif x == 94:
        print('The number is even')
    elif x == 95:
        print('The number is odd')
    elif x == 96:
        print('The number is even')
    elif x == 97:
        print('The number is odd')
    elif x == 98:
        print('The number is even')
    elif x == 99:
        print('The number is odd')
    elif x == 100:
        print('The number is even')
    elif x == 101:
        print('The number is odd')
    elif x == 102:
        print('The number is even')
    elif x == 103:
        print('The number is odd')
    elif x == 104:
        print('The number is even')
    elif x == 105:
        print('The number is odd')
    elif x == 106:
        print('The number is even')
    elif x == 107:
        print('The number is odd')
    elif x == 108:
        print('The number is even')
    elif x == 109:
        print('The number is odd')
    elif x == 110:
        print('The number is even')
    elif x == 111:
        print('The number is odd')
    elif x == 112:
        print('The number is even')
    elif x == 113:
        print('The number is odd')
    elif x == 114:
        print('The number is even')
    elif x == 115:
        print('The number is odd')
    elif x == 116:
        print('The number is even')
    elif x == 117:
        print('The number is odd')
    elif x == 118:
        print('The number is even')
    elif x == 119:
        print('The number is odd')
    elif x == 120:
        print('The number is even')
    elif x == 121:
        print('The number is odd')
    elif x == 122:
        print('The number is even')
    elif x == 123:
        print('The number is odd')
    elif x == 124:
        print('The number is even')
    elif x == 125:
        print('The number is odd')
    elif x == 126:
        print('The number is even')
    elif x == 127:
        print('The number is odd')
    elif x == 128:
        print('The number is even')
    elif x == 129:
        print('The number is odd')
    elif x == 130:
        print('The number is even')
    elif x == 131:
        print('The number is odd')
    elif x == 132:
        print('The number is even')
    elif x == 133:
        print('The number is odd')
    elif x == 134:
        print('The number is even')
    elif x == 135:
        print('The number is odd')
    elif x == 136:
        print('The number is even')
    elif x == 137:
        print('The number is odd')
    elif x == 138:
        print('The number is even')
    elif x == 139:
        print('The number is odd')
    elif x == 140:
        print('The number is even')
    elif x == 141:
        print('The number is odd')
    elif x == 142:
        print('The number is even')
    elif x == 143:
        print('The number is odd')
    elif x == 144:
        print('The number is even')
    elif x == 145:
        print('The number is odd')
    elif x == 146:
        print('The number is even')
    elif x == 147:
        print('The number is odd')
    elif x == 148:
        print('The number is even')
    elif x == 149:
        print('The number is odd')
    elif x == 150:
        print('The number is even')
    elif x == 151:
        print('The number is odd')
    elif x == 152:
        print('The number is even')
    elif x == 153:
        print('The number is odd')
    elif x == 154:
        print('The number is even')
    elif x == 155:
        print('The number is odd')
    elif x == 156:
        print('The number is even')
    elif x == 157:
        print('The number is odd')
    elif x == 158:
        print('The number is even')
    elif x == 159:
        print('The number is odd')
    elif x == 160:
        print('The number is even')
    elif x == 161:
        print('The number is odd')
    elif x == 162:
        print('The number is even')
    elif x == 163:
        print('The number is odd')
    elif x == 164:
        print('The number is even')
    elif x == 165:
        print('The number is odd')
    elif x == 166:
        print('The number is even')
    elif x == 167:
        print('The number is odd')
    elif x == 168:
        print('The number is even')
    elif x == 169:
        print('The number is odd')
    elif x == 170:
        print('The number is even')
    elif x == 171:
        print('The number is odd')
    elif x == 172:
        print('The number is even')
    elif x == 173:
        print('The number is odd')
    elif x == 174:
        print('The number is even')
    elif x == 175:
        print('The number is odd')
    elif x == 176:
        print('The number is even')
    elif x == 177:
        print('The number is odd')
    elif x == 178:
        print('The number is even')
    elif x == 179:
        print('The number is odd')
    elif x == 180:
        print('The number is even')
    elif x == 181:
        print('The number is odd')
    elif x == 182:
        print('The number is even')
    elif x == 183:
        print('The number is odd')
    elif x == 184:
        print('The number is even')
    elif x == 185:
        print('The number is odd')
    elif x == 186:
        print('The number is even')
    elif x == 187:
        print('The number is odd')
    elif x == 188:
        print('The number is even')
    elif x == 189:
        print('The number is odd')
    elif x == 190:
        print('The number is even')
    elif x == 191:
        print('The number is odd')
    elif x == 192:
        print('The number is even')
    elif x == 193:
        print('The number is odd')
    elif x == 194:
        print('The number is even')
    elif x == 195:
        print('The number is odd')
    elif x == 196:
        print('The number is even')
    elif x == 197:
        print('The number is odd')
    elif x == 198:
        print('The number is even')
    elif x == 199:
        print('The number is odd')
    elif x == 200:
        print('The number is even')
    elif x == 201:
        print('The number is odd')
    elif x == 202:
        print('The number is even')
    elif x == 203:
        print('The number is odd')
    elif x == 204:
        print('The number is even')
    elif x == 205:
        print('The number is odd')
    elif x == 206:
        print('The number is even')
    elif x == 207:
        print('The number is odd')
    elif x == 208:
        print('The number is even')
    elif x == 209:
        print('The number is odd')
    elif x == 210:
        print('The number is even')
    elif x == 211:
        print('The number is odd')
    elif x == 212:
        print('The number is even')
    elif x == 213:
        print('The number is odd')
    elif x == 214:
        print('The number is even')
    elif x == 215:
        print('The number is odd')
    elif x == 216:
        print('The number is even')
    elif x == 217:
        print('The number is odd')
    elif x == 218:
        print('The number is even')
    elif x == 219:
        print('The number is odd')
    elif x == 220:
        print('The number is even')
    elif x == 221:
        print('The number is odd')
    elif x == 222:
        print('The number is even')
    elif x == 223:
        print('The number is odd')
    elif x == 224:
        print('The number is even')
    elif x == 225:
        print('The number is odd')
    elif x == 226:
        print('The number is even')
    elif x == 227:
        print('The number is odd')
    elif x == 228:
        print('The number is even')
    elif x == 229:
        print('The number is odd')
    elif x == 230:
        print('The number is even')
    elif x == 231:
        print('The number is odd')
    elif x == 232:
        print('The number is even')
    elif x == 233:
        print('The number is odd')
    elif x == 234:
        print('The number is even')
    elif x == 235:
        print('The number is odd')
    elif x == 236:
        print('The number is even')
    elif x == 237:
        print('The number is odd')
    elif x == 238:
        print('The number is even')
    elif x == 239:
        print('The number is odd')
    elif x == 240:
        print('The number is even')
    elif x == 241:
        print('The number is odd')
    elif x == 242:
        print('The number is even')
    elif x == 243:
        print('The number is odd')
    elif x == 244:
        print('The number is even')
    elif x == 245:
        print('The number is odd')
    elif x == 246:
        print('The number is even')
    elif x == 247:
        print('The number is odd')
    elif x == 248:
        print('The number is even')
    elif x == 249:
        print('The number is odd')
    elif x == 250:
        print('The number is even')
    elif x == 251:
        print('The number is odd')
    elif x == 252:
        print('The number is even')
    elif x == 253:
        print('The number is odd')
    elif x == 254:
        print('The number is even')
    elif x == 255:
        print('The number is odd')
    elif x == 256:
        print('The number is even')
    elif x == 257:
        print('The number is odd')
    elif x == 258:
        print('The number is even')
    elif x == 259:
        print('The number is odd')
    elif x == 260:
        print('The number is even')
    elif x == 261:
        print('The number is odd')
    elif x == 262:
        print('The number is even')
    elif x == 263:
        print('The number is odd')
    elif x == 264:
        print('The number is even')
    elif x == 265:
        print('The number is odd')
    elif x == 266:
        print('The number is even')
    elif x == 267:
        print('The number is odd')
    elif x == 268:
        print('The number is even')
    elif x == 269:
        print('The number is odd')
    elif x == 270:
        print('The number is even')
    elif x == 271:
        print('The number is odd')
    elif x == 272:
        print('The number is even')
    elif x == 273:
        print('The number is odd')
    elif x == 274:
        print('The number is even')
    elif x == 275:
        print('The number is odd')
    elif x == 276:
        print('The number is even')
    elif x == 277:
        print('The number is odd')
    elif x == 278:
        print('The number is even')
    elif x == 279:
        print('The number is odd')
    elif x == 280:
        print('The number is even')
    elif x == 281:
        print('The number is odd')
    elif x == 282:
        print('The number is even')
    elif x == 283:
        print('The number is odd')
    elif x == 284:
        print('The number is even')
    elif x == 285:
        print('The number is odd')
    elif x == 286:
        print('The number is even')
    elif x == 287:
        print('The number is odd')
    elif x == 288:
        print('The number is even')
    elif x == 289:
        print('The number is odd')
    elif x == 290:
        print('The number is even')
    elif x == 291:
        print('The number is odd')
    elif x == 292:
        print('The number is even')
    elif x == 293:
        print('The number is odd')
    elif x == 294:
        print('The number is even')
    elif x == 295:
        print('The number is odd')
    elif x == 296:
        print('The number is even')
    elif x == 297:
        print('The number is odd')
    elif x == 298:
        print('The number is even')
    elif x == 299:
        print('The number is odd')
    elif x == 300:
        print('The number is even')
    elif x == 301:
        print('The number is odd')
    elif x == 302:
        print('The number is even')
    elif x == 303:
        print('The number is odd')
    elif x == 304:
        print('The number is even')
    elif x == 305:
        print('The number is odd')
    elif x == 306:
        print('The number is even')
    elif x == 307:
        print('The number is odd')
    elif x == 308:
        print('The number is even')
    elif x == 309:
        print('The number is odd')
    elif x == 310:
        print('The number is even')
    elif x == 311:
        print('The number is odd')
    elif x == 312:
        print('The number is even')
    elif x == 313:
        print('The number is odd')
    elif x == 314:
        print('The number is even')
    elif x == 315:
        print('The number is odd')
    elif x == 316:
        print('The number is even')
    elif x == 317:
        print('The number is odd')
    elif x == 318:
        print('The number is even')
    elif x == 319:
        print('The number is odd')
    elif x == 320:
        print('The number is even')
    elif x == 321:
        print('The number is odd')
    elif x == 322:
        print('The number is even')
    elif x == 323:
        print('The number is odd')
    elif x == 324:
        print('The number is even')
    elif x == 325:
        print('The number is odd')
    elif x == 326:
        print('The number is even')
    elif x == 327:
        print('The number is odd')
    elif x == 328:
        print('The number is even')
    elif x == 329:
        print('The number is odd')
    elif x == 330:
        print('The number is even')
    elif x == 331:
        print('The number is odd')
    elif x == 332:
        print('The number is even')
    elif x == 333:
        print('The number is odd')
    elif x == 334:
        print('The number is even')
    elif x == 335:
        print('The number is odd')
    elif x == 336:
        print('The number is even')
    elif x == 337:
        print('The number is odd')
    elif x == 338:
        print('The number is even')
    elif x == 339:
        print('The number is odd')
    elif x == 340:
        print('The number is even')
    elif x == 341:
        print('The number is odd')
    elif x == 342:
        print('The number is even')
    elif x == 343:
        print('The number is odd')
    elif x == 344:
        print('The number is even')
    elif x == 345:
        print('The number is odd')
    elif x == 346:
        print('The number is even')
    elif x == 347:
        print('The number is odd')
    elif x == 348:
        print('The number is even')
    elif x == 349:
        print('The number is odd')
    elif x == 350:
        print('The number is even')
    elif x == 351:
        print('The number is odd')
    elif x == 352:
        print('The number is even')
    elif x == 353:
        print('The number is odd')
    elif x == 354:
        print('The number is even')
    elif x == 355:
        print('The number is odd')
    elif x == 356:
        print('The number is even')
    elif x == 357:
        print('The number is odd')
    elif x == 358:
        print('The number is even')
    elif x == 359:
        print('The number is odd')
    elif x == 360:
        print('The number is even')
    elif x == 361:
        print('The number is odd')
    elif x == 362:
        print('The number is even')
    elif x == 363:
        print('The number is odd')
    elif x == 364:
        print('The number is even')
    elif x == 365:
        print('The number is odd')
    elif x == 366:
        print('The number is even')
    elif x == 367:
        print('The number is odd')
    elif x == 368:
        print('The number is even')
    elif x == 369:
        print('The number is odd')
    elif x == 370:
        print('The number is even')
    elif x == 371:
        print('The number is odd')
    elif x == 372:
        print('The number is even')
    elif x == 373:
        print('The number is odd')
    elif x == 374:
        print('The number is even')
    elif x == 375:
        print('The number is odd')
    elif x == 376:
        print('The number is even')
    elif x == 377:
        print('The number is odd')
    elif x == 378:
        print('The number is even')
    elif x == 379:
        print('The number is odd')
    elif x == 380:
        print('The number is even')
    elif x == 381:
        print('The number is odd')
    elif x == 382:
        print('The number is even')
    elif x == 383:
        print('The number is odd')
    elif x == 384:
        print('The number is even')
    elif x == 385:
        print('The number is odd')
    elif x == 386:
        print('The number is even')
    elif x == 387:
        print('The number is odd')
    elif x == 388:
        print('The number is even')
    elif x == 389:
        print('The number is odd')
    elif x == 390:
        print('The number is even')
    elif x == 391:
        print('The number is odd')
    elif x == 392:
        print('The number is even')
    elif x == 393:
        print('The number is odd')
    elif x == 394:
        print('The number is even')
    elif x == 395:
        print('The number is odd')
    elif x == 396:
        print('The number is even')
    elif x == 397:
        print('The number is odd')
    elif x == 398:
        print('The number is even')
    elif x == 399:
        print('The number is odd')
    elif x == 400:
        print('The number is even')
    elif x == 401:
        print('The number is odd')
    elif x == 402:
        print('The number is even')
    elif x == 403:
        print('The number is odd')
    elif x == 404:
        print('The number is even')
    elif x == 405:
        print('The number is odd')
    elif x == 406:
        print('The number is even')
    elif x == 407:
        print('The number is odd')
    elif x == 408:
        print('The number is even')
    elif x == 409:
        print('The number is odd')
    elif x == 410:
        print('The number is even')
    elif x == 411:
        print('The number is odd')
    elif x == 412:
        print('The number is even')
    elif x == 413:
        print('The number is odd')
    elif x == 414:
        print('The number is even')
    elif x == 415:
        print('The number is odd')
    elif x == 416:
        print('The number is even')
    elif x == 417:
        print('The number is odd')
    elif x == 418:
        print('The number is even')
    elif x == 419:
        print('The number is odd')
    elif x == 420:
        print('The number is even')
    elif x == 421:
        print('The number is odd')
    elif x == 422:
        print('The number is even')
    elif x == 423:
        print('The number is odd')
    elif x == 424:
        print('The number is even')
    elif x == 425:
        print('The number is odd')
    elif x == 426:
        print('The number is even')
    elif x == 427:
        print('The number is odd')
    elif x == 428:
        print('The number is even')
    elif x == 429:
        print('The number is odd')
    elif x == 430:
        print('The number is even')
    elif x == 431:
        print('The number is odd')
    elif x == 432:
        print('The number is even')
    elif x == 433:
        print('The number is odd')
    elif x == 434:
        print('The number is even')
    elif x == 435:
        print('The number is odd')
    elif x == 436:
        print('The number is even')
    elif x == 437:
        print('The number is odd')
    elif x == 438:
        print('The number is even')
    elif x == 439:
        print('The number is odd')
    elif x == 440:
        print('The number is even')
    elif x == 441:
        print('The number is odd')
    elif x == 442:
        print('The number is even')
    elif x == 443:
        print('The number is odd')
    elif x == 444:
        print('The number is even')
    elif x == 445:
        print('The number is odd')
    elif x == 446:
        print('The number is even')
    elif x == 447:
        print('The number is odd')
    elif x == 448:
        print('The number is even')
    elif x == 449:
        print('The number is odd')
    elif x == 450:
        print('The number is even')
    elif x == 451:
        print('The number is odd')
    elif x == 452:
        print('The number is even')
    elif x == 453:
        print('The number is odd')
    elif x == 454:
        print('The number is even')
    elif x == 455:
        print('The number is odd')
    elif x == 456:
        print('The number is even')
    elif x == 457:
        print('The number is odd')
    elif x == 458:
        print('The number is even')
    elif x == 459:
        print('The number is odd')
    elif x == 460:
        print('The number is even')
    elif x == 461:
        print('The number is odd')
    elif x == 462:
        print('The number is even')
    elif x == 463:
        print('The number is odd')
    elif x == 464:
        print('The number is even')
    elif x == 465:
        print('The number is odd')
    elif x == 466:
        print('The number is even')
    elif x == 467:
        print('The number is odd')
    elif x == 468:
        print('The number is even')
    elif x == 469:
        print('The number is odd')
    elif x == 470:
        print('The number is even')
    elif x == 471:
        print('The number is odd')
    elif x == 472:
        print('The number is even')
    elif x == 473:
        print('The number is odd')
    elif x == 474:
        print('The number is even')
    elif x == 475:
        print('The number is odd')
    elif x == 476:
        print('The number is even')
    elif x == 477:
        print('The number is odd')
    elif x == 478:
        print('The number is even')
    elif x == 479:
        print('The number is odd')
    elif x == 480:
        print('The number is even')
    elif x == 481:
        print('The number is odd')
    elif x == 482:
        print('The number is even')
    elif x == 483:
        print('The number is odd')
    elif x == 484:
        print('The number is even')
    elif x == 485:
        print('The number is odd')
    elif x == 486:
        print('The number is even')
    elif x == 487:
        print('The number is odd')
    elif x == 488:
        print('The number is even')
    elif x == 489:
        print('The number is odd')
    elif x == 490:
        print('The number is even')
    elif x == 491:
        print('The number is odd')
    elif x == 492:
        print('The number is even')
    elif x == 493:
        print('The number is odd')
    elif x == 494:
        print('The number is even')
    elif x == 495:
        print('The number is odd')
    elif x == 496:
        print('The number is even')
    elif x == 497:
        print('The number is odd')
    elif x == 498:
        print('The number is even')
    elif x == 499:
        print('The number is odd')
    elif x == 500:
        print('The number is even')
    elif x == 501:
        print('The number is odd')
    elif x == 502:
        print('The number is even')
    elif x == 503:
        print('The number is odd')
    elif x == 504:
        print('The number is even')
    elif x == 505:
        print('The number is odd')
    elif x == 506:
        print('The number is even')
    elif x == 507:
        print('The number is odd')
    elif x == 508:
        print('The number is even')
    elif x == 509:
        print('The number is odd')
    elif x == 510:
        print('The number is even')
    elif x == 511:
        print('The number is odd')
    elif x == 512:
        print('The number is even')
    elif x == 513:
        print('The number is odd')
    elif x == 514:
        print('The number is even')
    elif x == 515:
        print('The number is odd')
    elif x == 516:
        print('The number is even')
    elif x == 517:
        print('The number is odd')
    elif x == 518:
        print('The number is even')
    elif x == 519:
        print('The number is odd')
    elif x == 520:
        print('The number is even')
    elif x == 521:
        print('The number is odd')
    elif x == 522:
        print('The number is even')
    elif x == 523:
        print('The number is odd')
    elif x == 524:
        print('The number is even')
    elif x == 525:
        print('The number is odd')
    elif x == 526:
        print('The number is even')
    elif x == 527:
        print('The number is odd')
    elif x == 528:
        print('The number is even')
    elif x == 529:
        print('The number is odd')
    elif x == 530:
        print('The number is even')
    elif x == 531:
        print('The number is odd')
    elif x == 532:
        print('The number is even')
    elif x == 533:
        print('The number is odd')
    elif x == 534:
        print('The number is even')
    elif x == 535:
        print('The number is odd')
    elif x == 536:
        print('The number is even')
    elif x == 537:
        print('The number is odd')
    elif x == 538:
        print('The number is even')
    elif x == 539:
        print('The number is odd')
    elif x == 540:
        print('The number is even')
    elif x == 541:
        print('The number is odd')
    elif x == 542:
        print('The number is even')
    elif x == 543:
        print('The number is odd')
    elif x == 544:
        print('The number is even')
    elif x == 545:
        print('The number is odd')
    elif x == 546:
        print('The number is even')
    elif x == 547:
        print('The number is odd')
    elif x == 548:
        print('The number is even')
    elif x == 549:
        print('The number is odd')
    elif x == 550:
        print('The number is even')
    elif x == 551:
        print('The number is odd')
    elif x == 552:
        print('The number is even')
    elif x == 553:
        print('The number is odd')
    elif x == 554:
        print('The number is even')
    elif x == 555:
        print('The number is odd')
    elif x == 556:
        print('The number is even')
    elif x == 557:
        print('The number is odd')
    elif x == 558:
        print('The number is even')
    elif x == 559:
        print('The number is odd')
    elif x == 560:
        print('The number is even')
    elif x == 561:
        print('The number is odd')
    elif x == 562:
        print('The number is even')
    elif x == 563:
        print('The number is odd')
    elif x == 564:
        print('The number is even')
    elif x == 565:
        print('The number is odd')
    elif x == 566:
        print('The number is even')
    elif x == 567:
        print('The number is unholy.')
    elif x == 568:
        print('The number is even')
    elif x == 569:
        print('The number is funny :)')
    elif x == 570:
        print('The number is even')
    elif x == 571:
        print('The number is odd')
    elif x == 572:
        print('The number is even')
    elif x == 573:
        print('The number is odd')
    elif x == 574:
        print('The number is even')
    elif x == 575:
        print('The number is odd')
    elif x == 576:
        print('The number is even')
    elif x == 577:
        print('The number is odd')
    elif x == 578:
        print('The number is even')
    elif x == 579:
        print('The number is odd')
    elif x == 580:
        print('The number is even')
    elif x == 581:
        print('The number is odd')
    elif x == 582:
        print('The number is even')
    elif x == 583:
        print('The number is odd')
    elif x == 584:
        print('The number is even')
    elif x == 585:
        print('The number is odd')
    elif x == 586:
        print('The number is even')
    elif x == 587:
        print('The number is odd')
    elif x == 588:
        print('The number is even')
    elif x == 589:
        print('The number is odd')
    elif x == 590:
        print('The number is even')
    elif x == 591:
        print('The number is odd')
    elif x == 592:
        print('The number is even')
    elif x == 593:
        print('The number is odd')
    elif x == 594:
        print('The number is even')
    elif x == 595:
        print('The number is odd')
    elif x == 596:
        print('The number is even')
    elif x == 597:
        print('The number is odd')
    elif x == 598:
        print('The number is even')
    elif x == 599:
        print('The number is odd')
    elif x == 600:
        print('The number is even')
    elif x == 601:
        print('The number is odd')
    elif x == 602:
        print('The number is even')
    elif x == 603:
        print('The number is odd')
    elif x == 604:
        print('The number is even')
    elif x == 605:
        print('The number is odd')
    elif x == 606:
        print('The number is even')
    elif x == 607:
        print('The number is odd')
    elif x == 608:
        print('The number is even')
    elif x == 609:
        print('The number is odd')
    elif x == 610:
        print('The number is even')
    elif x == 611:
        print('The number is odd')
    elif x == 612:
        print('The number is even')
    elif x == 613:
        print('The number is odd')
    elif x == 614:
        print('The number is even')
    elif x == 615:
        print('The number is odd')
    elif x == 616:
        print('The number is even')
    elif x == 617:
        print('The number is odd')
    elif x == 618:
        print('The number is even')
    elif x == 619:
        print('The number is odd')
    elif x == 620:
        print('The number is even')
    elif x == 621:
        print('The number is odd')
    elif x == 622:
        print('The number is even')
    elif x == 623:
        print('The number is odd')
    elif x == 624:
        print('The number is even')
    elif x == 625:
        print('The number is odd')
    elif x == 626:
        print('The number is even')
    elif x == 627:
        print('The number is odd')
    elif x == 628:
        print('The number is even')
    elif x == 629:
        print('The number is odd')
    elif x == 630:
        print('The number is even')
    elif x == 631:
        print('The number is odd')
    elif x == 632:
        print('The number is even')
    elif x == 633:
        print('The number is odd')
    elif x == 634:
        print('The number is even')
    elif x == 635:
        print('The number is odd')
    elif x == 636:
        print('The number is even')
    elif x == 637:
        print('The number is odd')
    elif x == 638:
        print('The number is even')
    elif x == 639:
        print('The number is odd')
    elif x == 640:
        print('The number is even')
    elif x == 641:
        print('The number is odd')
    elif x == 642:
        print('The number is even')
    elif x == 643:
        print('The number is odd')
    elif x == 644:
        print('The number is even')
    elif x == 645:
        print('The number is odd')
    elif x == 646:
        print('The number is even')
    elif x == 647:
        print('The number is odd')
    elif x == 648:
        print('The number is even')
    elif x == 649:
        print('The number is odd')
    elif x == 650:
        print('The number is even')
    elif x == 651:
        print('The number is odd')
    elif x == 652:
        print('The number is even')
    elif x == 653:
        print('The number is odd')
    elif x == 654:
        print('The number is even')
    elif x == 655:
        print('The number is odd')
    elif x == 656:
        print('The number is even')
    elif x == 657:
        print('The number is odd')
    elif x == 658:
        print('The number is even')
    elif x == 659:
        print('The number is odd')
    elif x == 660:
        print('The number is even')
    elif x == 661:
        print('The number is odd')
    elif x == 662:
        print('The number is even')
    elif x == 663:
        print('The number is odd')
    elif x == 664:
        print('The number is even')
    elif x == 665:
        print('The number is odd')
    elif x == 666:
        print('The number is even')
    elif x == 667:
        print('The number is odd')
    elif x == 668:
        print('The number is even')
    elif x == 669:
        print('The number is odd')
    elif x == 670:
        print('The number is even')
    elif x == 671:
        print('The number is odd')
    elif x == 672:
        print('The number is even')
    elif x == 673:
        print('The number is odd')
    elif x == 674:
        print('The number is even')
    elif x == 675:
        print('The number is odd')
    elif x == 676:
        print('The number is even')
    elif x == 677:
        print('The number is odd')
    elif x == 678:
        print('The number is even')
    elif x == 679:
        print('The number is odd')
    elif x == 680:
        print('The number is even')
    elif x == 681:
        print('The number is odd')
    elif x == 682:
        print('The number is even')
    elif x == 683:
        print('The number is odd')
    elif x == 684:
        print('The number is even')
    elif x == 685:
        print('The number is odd')
    elif x == 686:
        print('The number is even')
    elif x == 687:
        print('The number is odd')
    elif x == 688:
        print('The number is even')
    elif x == 689:
        print('The number is odd')
    elif x == 690:
        print('The number is even')
    elif x == 691:
        print('The number is odd')
    elif x == 692:
        print('The number is even')
    elif x == 693:
        print('The number is odd')
    elif x == 694:
        print('The number is even')
    elif x == 695:
        print('The number is odd')
    elif x == 696:
        print('The number is even')
    elif x == 697:
        print('The number is odd')
    elif x == 698:
        print('The number is even')
    elif x == 699:
        print('The number is odd')
    elif x == 700:
        print('The number is even')
    elif x == 701:
        print('The number is odd')
    elif x == 702:
        print('The number is even')
    elif x == 703:
        print('The number is odd')
    elif x == 704:
        print('The number is even')
    elif x == 705:
        print('The number is odd')
    elif x == 706:
        print('The number is even')
    elif x == 707:
        print('The number is odd')
    elif x == 708:
        print('The number is even')
    elif x == 709:
        print('The number is odd')
    elif x == 710:
        print('The number is even')
    elif x == 711:
        print('The number is odd')
    elif x == 712:
        print('The number is even')
    elif x == 713:
        print('The number is odd')
    elif x == 714:
        print('The number is even')
    elif x == 715:
        print('The number is odd')
    elif x == 716:
        print('The number is even')
    elif x == 717:
        print('The number is odd')
    elif x == 718:
        print('The number is even')
    elif x == 719:
        print('The number is odd')
    elif x == 720:
        print('The number is even')
    elif x == 721:
        print('The number is odd')
    elif x == 722:
        print('The number is even')
    elif x == 723:
        print('The number is odd')
    elif x == 724:
        print('The number is even')
    elif x == 725:
        print('The number is odd')
    elif x == 726:
        print('The number is even')
    elif x == 727:
        print('The number is odd')
    elif x == 728:
        print('The number is even')
    elif x == 729:
        print('The number is odd')
    elif x == 730:
        print('The number is even')
    elif x == 731:
        print('The number is odd')
    elif x == 732:
        print('The number is even')
    elif x == 733:
        print('The number is odd')
    elif x == 734:
        print('The number is even')
    elif x == 735:
        print('The number is odd')
    elif x == 736:
        print('The number is even')
    elif x == 737:
        print('The number is odd')
    elif x == 738:
        print('The number is even')
    elif x == 739:
        print('The number is odd')
    elif x == 740:
        print('The number is even')
    elif x == 741:
        print('The number is odd')
    elif x == 742:
        print('The number is even')
    elif x == 743:
        print('The number is odd')
    elif x == 744:
        print('The number is even')
    elif x == 745:
        print('The number is odd')
    elif x == 746:
        print('The number is even')
    elif x == 747:
        print('The number is odd')
    elif x == 748:
        print('The number is even')
    elif x == 749:
        print('The number is odd')
    elif x == 750:
        print('The number is even')
    elif x == 751:
        print('The number is odd')
    elif x == 752:
        print('The number is even')
    elif x == 753:
        print('The number is odd')
    elif x == 754:
        print('The number is even')
    elif x == 755:
        print('The number is odd')
    elif x == 756:
        print('The number is even')
    elif x == 757:
        print('The number is odd')
    elif x == 758:
        print('The number is even')
    elif x == 759:
        print('The number is odd')
    elif x == 760:
        print('The number is even')
    elif x == 761:
        print('The number is odd')
    elif x == 762:
        print('The number is even')
    elif x == 763:
        print('The number is odd')
    elif x == 764:
        print('The number is even')
    elif x == 765:
        print('The number is odd')
    elif x == 766:
        print('The number is even')
    elif x == 767:
        print('The number is odd')
    elif x == 768:
        print('The number is even')
    elif x == 769:
        print('The number is odd')
    elif x == 770:
        print('The number is even')
    elif x == 771:
        print('The number is odd')
    elif x == 772:
        print('The number is even')
    elif x == 773:
        print('The number is odd')
    elif x == 774:
        print('The number is even')
    elif x == 775:
        print('The number is odd')
    elif x == 776:
        print('The number is even')
    elif x == 777:
        print('The number is odd')
    elif x == 778:
        print('The number is even')
    elif x == 779:
        print('The number is odd')
    elif x == 780:
        print('The number is even')
    elif x == 781:
        print('The number is odd')
    elif x == 782:
        print('The number is even')
    elif x == 783:
        print('The number is odd')
    elif x == 784:
        print('The number is even')
    elif x == 785:
        print('The number is odd')
    elif x == 786:
        print('The number is even')
    elif x == 787:
        print('The number is odd')
    elif x == 788:
        print('The number is even')
    elif x == 789:
        print('The number is odd')
    elif x == 790:
        print('The number is even')
    elif x == 791:
        print('The number is odd')
    elif x == 792:
        print('The number is even')
    elif x == 793:
        print('The number is odd')
    elif x == 794:
        print('The number is even')
    elif x == 795:
        print('The number is odd')
    elif x == 796:
        print('The number is even')
    elif x == 797:
        print('The number is odd')
    elif x == 798:
        print('The number is even')
    elif x == 799:
        print('The number is odd')
    elif x == 800:
        print('The number is even')
    elif x == 801:
        print('The number is odd')
    elif x == 802:
        print('The number is even')
    elif x == 803:
        print('The number is odd')
    elif x == 804:
        print('The number is even')
    elif x == 805:
        print('The number is odd')
    elif x == 806:
        print('The number is even')
    elif x == 807:
        print('The number is odd')
    elif x == 808:
        print('The number is even')
    elif x == 809:
        print('The number is odd')
    elif x == 810:
        print('The number is even')
    elif x == 811:
        print('The number is odd')
    elif x == 812:
        print('The number is even')
    elif x == 813:
        print('The number is odd')
    elif x == 814:
        print('The number is even')
    elif x == 815:
        print('The number is odd')
    elif x == 816:
        print('The number is even')
    elif x == 817:
        print('The number is odd')
    elif x == 818:
        print('The number is even')
    elif x == 819:
        print('The number is odd')
    elif x == 820:
        print('The number is even')
    elif x == 821:
        print('The number is odd')
    elif x == 822:
        print('The number is even')
    elif x == 823:
        print('The number is odd')
    elif x == 824:
        print('The number is even')
    elif x == 825:
        print('The number is odd')
    elif x == 826:
        print('The number is even')
    elif x == 827:
        print('The number is odd')
    elif x == 828:
        print('The number is even')
    elif x == 829:
        print('The number is odd')
    elif x == 830:
        print('The number is even')
    elif x == 831:
        print('The number is odd')
    elif x == 832:
        print('The number is even')
    elif x == 833:
        print('The number is odd')
    elif x == 834:
        print('The number is even')
    elif x == 835:
        print('The number is odd')
    elif x == 836:
        print('The number is even')
    elif x == 837:
        print('The number is odd')
    elif x == 838:
        print('The number is even')
    elif x == 839:
        print('The number is odd')
    elif x == 840:
        print('The number is even')
    elif x == 841:
        print('The number is odd')
    elif x == 842:
        print('The number is even')
    elif x == 843:
        print('The number is odd')
    elif x == 844:
        print('The number is even')
    elif x == 845:
        print('The number is odd')
    elif x == 846:
        print('The number is even')
    elif x == 847:
        print('The number is odd')
    elif x == 848:
        print('The number is even')
    elif x == 849:
        print('The number is odd')
    elif x == 850:
        print('The number is even')
    elif x == 851:
        print('The number is odd')
    elif x == 852:
        print('The number is even')
    elif x == 853:
        print('The number is odd')
    elif x == 854:
        print('The number is even')
    elif x == 855:
        print('The number is odd')
    elif x == 856:
        print('The number is even')
    elif x == 857:
        print('The number is odd')
    elif x == 858:
        print('The number is even')
    elif x == 859:
        print('The number is odd')
    elif x == 860:
        print('The number is even')
    elif x == 861:
        print('The number is odd')
    elif x == 862:
        print('The number is even')
    elif x == 863:
        print('The number is odd')
    elif x == 864:
        print('The number is even')
    elif x == 865:
        print('The number is odd')
    elif x == 866:
        print('The number is even')
    elif x == 867:
        print('The number is odd')
    elif x == 868:
        print('The number is even')
    elif x == 869:
        print('The number is odd')
    elif x == 870:
        print('The number is even')
    elif x == 871:
        print('The number is odd')
    elif x == 872:
        print('The number is even')
    elif x == 873:
        print('The number is odd')
    elif x == 874:
        print('The number is even')
    elif x == 875:
        print('The number is odd')
    elif x == 876:
        print('The number is even')
    elif x == 877:
        print('The number is odd')
    elif x == 878:
        print('The number is even')
    elif x == 879:
        print('The number is odd')
    elif x == 880:
        print('The number is even')
    elif x == 881:
        print('The number is odd')
    elif x == 882:
        print('The number is even')
    elif x == 883:
        print('The number is odd')
    elif x == 884:
        print('The number is even')
    elif x == 885:
        print('The number is odd')
    elif x == 886:
        print('The number is even')
    elif x == 887:
        print('The number is odd')
    elif x == 888:
        print('The number is even')
    elif x == 889:
        print('The number is odd')
    elif x == 890:
        print('The number is even')
    elif x == 891:
        print('The number is odd')
    elif x == 892:
        print('The number is even')
    elif x == 893:
        print('The number is odd')
    elif x == 894:
        print('The number is even')
    elif x == 895:
        print('The number is odd')
    elif x == 896:
        print('The number is even')
    elif x == 897:
        print('The number is odd')
    elif x == 898:
        print('The number is even')
    elif x == 899:
        print('The number is odd')
    elif x == 900:
        print('The number is even')
    elif x == 901:
        print('The number is odd')
    elif x == 902:
        print('The number is even')
    elif x == 903:
        print('The number is odd')
    elif x == 904:
        print('The number is even')
    elif x == 905:
        print('The number is odd')
    elif x == 906:
        print('The number is even')
    elif x == 907:
        print('The number is odd')
    elif x == 908:
        print('The number is even')
    elif x == 909:
        print('The number is odd')
    elif x == 910:
        print('The number is even')
    elif x == 911:
        print('The number is odd')
    elif x == 912:
        print('The number is even')
    elif x == 913:
        print('The number is odd')
    elif x == 914:
        print('The number is even')
    elif x == 915:
        print('The number is odd')
    elif x == 916:
        print('The number is even')
    elif x == 917:
        print('The number is odd')
    elif x == 918:
        print('The number is even')
    elif x == 919:
        print('The number is odd')
    elif x == 920:
        print('The number is even')
    elif x == 921:
        print('The number is odd')
    elif x == 922:
        print('The number is even')
    elif x == 923:
        print('The number is odd')
    elif x == 924:
        print('The number is even')
    elif x == 925:
        print('The number is odd')
    elif x == 926:
        print('The number is even')
    elif x == 927:
        print('The number is odd')
    elif x == 928:
        print('The number is even')
    elif x == 929:
        print('The number is odd')
    elif x == 930:
        print('The number is even')
    elif x == 931:
        print('The number is odd')
    elif x == 932:
        print('The number is even')
    elif x == 933:
        print('The number is odd')
    elif x == 934:
        print('The number is even')
    elif x == 935:
        print('The number is odd')
    elif x == 936:
        print('The number is even')
    elif x == 937:
        print('The number is odd')
    elif x == 938:
        print('The number is even')
    elif x == 939:
        print('The number is odd')
    elif x == 940:
        print('The number is even')
    elif x == 941:
        print('The number is odd')
    elif x == 942:
        print('The number is even')
    elif x == 943:
        print('The number is odd')
    elif x == 944:
        print('The number is even')
    elif x == 945:
        print('The number is odd')
    elif x == 946:
        print('The number is even')
    elif x == 947:
        print('The number is odd')
    elif x == 948:
        print('The number is even')
    elif x == 949:
        print('The number is odd')
    elif x == 950:
        print('The number is even')
    elif x == 951:
        print('The number is odd')
    elif x == 952:
        print('The number is even')
    elif x == 953:
        print('The number is odd')
    elif x == 954:
        print('The number is even')
    elif x == 955:
        print('The number is odd')
    elif x == 956:
        print('The number is even')
    elif x == 957:
        print('The number is odd')
    elif x == 958:
        print('The number is even')
    elif x == 959:
        print('The number is odd')
    elif x == 960:
        print('The number is even')
    elif x == 961:
        print('The number is odd')
    elif x == 962:
        print('The number is even')
    elif x == 963:
        print('The number is odd')
    elif x == 964:
        print('The number is even')
    elif x == 965:
        print('The number is odd')
    elif x == 966:
        print('The number is even')
    elif x == 967:
        print('The number is odd')
    elif x == 968:
        print('The number is even')
    elif x == 969:
        print('The number is odd')
    elif x == 970:
        print('The number is even')
    elif x == 971:
        print('The number is odd')
    elif x == 972:
        print('The number is even')
    elif x == 973:
        print('The number is odd')
    elif x == 974:
        print('The number is even')
    elif x == 975:
        print('The number is odd')
    elif x == 976:
        print('The number is even')
    elif x == 977:
        print('The number is odd')
    elif x == 978:
        print('The number is even')
    elif x == 979:
        print('The number is odd')
    elif x == 980:
        print('The number is even')
    elif x == 981:
        print('The number is odd')
    elif x == 982:
        print('The number is even')
    elif x == 983:
        print('The number is odd')
    elif x == 984:
        print('The number is even')
    elif x == 985:
        print('The number is odd')
    elif x == 986:
        print('The number is even')
    elif x == 987:
        print('The number is odd')
    elif x == 988:
        print('The number is even')
    elif x == 989:
        print('The number is odd')
    elif x == 990:
        print('The number is even')
    elif x == 991:
        print('The number is odd')
    elif x == 992:
        print('The number is even')
    elif x == 993:
        print('The number is odd')
    elif x == 994:
        print('The number is even')
    elif x == 995:
        print('The number is odd')
    elif x == 996:
        print('The number is even')
    elif x == 997:
        print('The number is odd')
    elif x == 998:
        print('The number is even')
    elif x == 999:
        print('The number is odd')
    elif x == 1000:
        print('The number is even')