while True:
    x = int(input("Input a number: "))
    x = abs(x)
    if x == 0:
        print('The number is even')
    elif x == 1:
        print('The number is odd')
    elif x == 2:
        print('The number is even')
    elif x == 3:
        print('The number is odd')
    elif x == 4:
        print('The number is even')
    elif x == 5:
        print('The number is odd')
    elif x == 6:
        print('The number is even')
    elif x == 7:
        print('The number is odd')
    elif x == 8:
        print('The number is even')
    elif x == 9:
        print('The number is odd')
    elif x == 10:
        print('The number is even')
    elif x == 11:
        print('The number is odd')
    elif x == 12:
        print('The number is even')
    elif x == 13:
        print('The number is odd')
    elif x == 14:
        print('The number is even')
    elif x == 15:
        print('The number is odd')
    elif x == 16:
        print('The number is even')
    elif x == 17:
        print('The number is odd')
    elif x == 18:
        print('The number is even')
    elif x == 19:
        print('The number is odd')
    elif x == 20:
        print('The number is even')
    elif x == 21:
        print('The number is odd')
    elif x == 22:
        print('The number is even')
    elif x == 23:
        print('The number is odd')
    elif x == 24:
        print('The number is even')
    elif x == 25:
        print('The number is odd')
    elif x == 26:
        print('The number is even')
    elif x == 27:
        print('The number is odd')
    elif x == 28:
        print('The number is even')
    elif x == 29:
        print('The number is odd')
    elif x == 30:
        print('The number is even')
    elif x == 31:
        print('The number is odd')
    elif x == 32:
        print('The number is even')
    elif x == 33:
        print('The number is odd')
    elif x == 34:
        print('The number is even')
    elif x == 35:
        print('The number is odd')
    elif x == 36:
        print('The number is even')
    elif x == 37:
        print('The number is odd')
    elif x == 38:
        print('The number is even')
    elif x == 39:
        print('The number is odd')
    elif x == 40:
        print('The number is even')
    elif x == 41:
        print('The number is odd')
    elif x == 42:
        print('The number is even')
    elif x == 43:
        print('The number is odd')
    elif x == 44:
        print('The number is even')
    elif x == 45:
        print('The number is odd')
    elif x == 46:
        print('The number is even')
    elif x == 47:
        print('The number is odd')
    elif x == 48:
        print('The number is even')
    elif x == 49:
        print('The number is odd')
    elif x == 50:
        print('The number is even')
    elif x == 51:
        print('The number is odd')
    elif x == 52:
        print('The number is even')
    elif x == 53:
        print('The number is odd')
    elif x == 54:
        print('The number is even')
    elif x == 55:
        print('The number is odd')
    elif x == 56:
        print('The number is even')
    elif x == 57:
        print('The number is odd')
    elif x == 58:
        print('The number is even')
    elif x == 59:
        print('The number is odd')
    elif x == 60:
        print('The number is even')
    elif x == 61:
        print('The number is odd')
    elif x == 62:
        print('The number is even')
    elif x == 63:
        print('The number is odd')
    elif x == 64:
        print('The number is even')
    elif x == 65:
        print('The number is odd')
    elif x == 66:
        print('The number is even')
    elif x == 67:
        print('The number is unholy.')
    elif x == 68:
        print('The number is even')
    elif x == 69:
        print('The number is funny :)')
    elif x == 70:
        print('The number is even')
    elif x == 71:
        print('The number is odd')
    elif x == 72:
        print('The number is even')
    elif x == 73:
        print('The number is odd')
    elif x == 74:
        print('The number is even')
    elif x == 75:
        print('The number is odd')
    elif x == 76:
        print('The number is even')
    elif x == 77:
        print('The number is odd')
    elif x == 78:
        print('The number is even')
    elif x == 79:
        print('The number is odd')
    elif x == 80:
        print('The number is even')
    elif x == 81:
        print('The number is odd')
    elif x == 82:
        print('The number is even')
    elif x == 83:
        print('The number is odd')
    elif x == 84:
        print('The number is even')
    elif x == 85:
        print('The number is odd')
    elif x == 86:
        print('The number is even')
    elif x == 87:
        print('The number is odd')
    elif x == 88:
        print('The number is even')
    elif x == 89:
        print('The number is odd')
    elif x == 90:
        print('The number is even')
    elif x == 91:
        print('The number is odd')
    elif x == 92:
        print('The number is even')
    elif x == 93:
        print('The number is odd')
    elif x == 94:
        print('The number is even')
    elif x == 95:
        print('The number is odd')
    elif x == 96:
        print('The number is even')
    elif x == 97:
        print('The number is odd')
    elif x == 98:
        print('The number is even')
    elif x == 99:
        print('The number is odd')
    elif x == 100:
        print('The number is even')