while True:
    x = int(input("Input a number: "))
    x = abs(x)
    if x == 0:
        print('The number is even')
    elif x == 1:
        print('The number is odd')
    elif x == 2:
        print('The number is even')
    elif x == 3:
        print('The number is odd')
    elif x == 4:
        print('The number is even')
    elif x == 5:
        print('The number is odd')
    elif x == 6:
        print('The number is even')
    elif x == 7:
        print('The number is odd')
    elif x == 8:
        print('The number is even')
    elif x == 9:
        print('The number is odd')
    elif x == 10:
        print('The number is even')
    elif x == 11:
        print('The number is odd')
    elif x == 12:
        print('The number is even')
    elif x == 13:
        print('The number is odd')
    elif x == 14:
        print('The number is even')
    elif x == 15:
        print('The number is odd')
    elif x == 16:
        print('The number is even')
    elif x == 17:
        print('The number is odd')
    elif x == 18:
        print('The number is even')
    elif x == 19:
        print('The number is odd')
    elif x == 20:
        print('The number is even')
    elif x == 21:
        print('The number is odd')
    elif x == 22:
        print('The number is even')
    elif x == 23:
        print('The number is odd')
    elif x == 24:
        print('The number is even')
    elif x == 25:
        print('The number is odd')
    elif x == 26:
        print('The number is even')
    elif x == 27:
        print('The number is odd')
    elif x == 28:
        print('The number is even')
    elif x == 29:
        print('The number is odd')
    elif x == 30:
        print('The number is even')
    elif x == 31:
        print('The number is odd')
    elif x == 32:
        print('The number is even')
    elif x == 33:
        print('The number is odd')
    elif x == 34:
        print('The number is even')
    elif x == 35:
        print('The number is odd')
    elif x == 36:
        print('The number is even')
    elif x == 37:
        print('The number is odd')
    elif x == 38:
        print('The number is even')
    elif x == 39:
        print('The number is odd')
    elif x == 40:
        print('The number is even')
    elif x == 41:
        print('The number is odd')
    elif x == 42:
        print('The number is even')
    elif x == 43:
        print('The number is odd')
    elif x == 44:
        print('The number is even')
    elif x == 45:
        print('The number is odd')
    elif x == 46:
        print('The number is even')
    elif x == 47:
        print('The number is odd')
    elif x == 48:
        print('The number is even')
    elif x == 49:
        print('The number is odd')
    elif x == 50:
        print('The number is even')
    elif x == 51:
        print('The number is odd')
    elif x == 52:
        print('The number is even')
    elif x == 53:
        print('The number is odd')
    elif x == 54:
        print('The number is even')
    elif x == 55:
        print('The number is odd')
    elif x == 56:
        print('The number is even')
    elif x == 57:
        print('The number is odd')
    elif x == 58:
        print('The number is even')
    elif x == 59:
        print('The number is odd')
    elif x == 60:
        print('The number is even')
    elif x == 61:
        print('The number is odd')
    elif x == 62:
        print('The number is even')
    elif x == 63:
        print('The number is odd')
    elif x == 64:
        print('The number is even')
    elif x == 65:
        print('The number is odd')
    elif x == 66:
        print('The number is even')
    elif x == 67:
        print('The number is unholy.')
    elif x == 68:
        print('The number is even')
    elif x == 69:
        print('The number is funny :)')
    elif x == 70:
        print('The number is even')
    elif x == 71:
        print('The number is odd')
    elif x == 72:
        print('The number is even')
    elif x == 73:
        print('The number is odd')
    elif x == 74:
        print('The number is even')
    elif x == 75:
        print('The number is odd')
    elif x == 76:
        print('The number is even')
    elif x == 77:
        print('The number is odd')
    elif x == 78:
        print('The number is even')
    elif x == 79:
        print('The number is odd')
    elif x == 80:
        print('The number is even')
    elif x == 81:
        print('The number is odd')
    elif x == 82:
        print('The number is even')
    elif x == 83:
        print('The number is odd')
    elif x == 84:
        print('The number is even')
    elif x == 85:
        print('The number is odd')
    elif x == 86:
        print('The number is even')
    elif x == 87:
        print('The number is odd')
    elif x == 88:
        print('The number is even')
    elif x == 89:
        print('The number is odd')
    elif x == 90:
        print('The number is even')
    elif x == 91:
        print('The number is odd')
    elif x == 92:
        print('The number is even')
    elif x == 93:
        print('The number is odd')
    elif x == 94:
        print('The number is even')
    elif x == 95:
        print('The number is odd')
    elif x == 96:
        print('The number is even')
    elif x == 97:
        print('The number is odd')
    elif x == 98:
        print('The number is even')
    elif x == 99:
        print('The number is odd')
    elif x == 100:
        print('The number is even')
    elif x == 101:
        print('The number is odd')
    elif x == 102:
        print('The number is even')
    elif x == 103:
        print('The number is odd')
    elif x == 104:
        print('The number is even')
    elif x == 105:
        print('The number is odd')
    elif x == 106:
        print('The number is even')
    elif x == 107:
        print('The number is odd')
    elif x == 108:
        print('The number is even')
    elif x == 109:
        print('The number is odd')
    elif x == 110:
        print('The number is even')
    elif x == 111:
        print('The number is odd')
    elif x == 112:
        print('The number is even')
    elif x == 113:
        print('The number is odd')
    elif x == 114:
        print('The number is even')
    elif x == 115:
        print('The number is odd')
    elif x == 116:
        print('The number is even')
    elif x == 117:
        print('The number is odd')
    elif x == 118:
        print('The number is even')
    elif x == 119:
        print('The number is odd')
    elif x == 120:
        print('The number is even')
    elif x == 121:
        print('The number is odd')
    elif x == 122:
        print('The number is even')
    elif x == 123:
        print('The number is odd')
    elif x == 124:
        print('The number is even')
    elif x == 125:
        print('The number is odd')
    elif x == 126:
        print('The number is even')
    elif x == 127:
        print('The number is odd')
    elif x == 128:
        print('The number is even')
    elif x == 129:
        print('The number is odd')
    elif x == 130:
        print('The number is even')
    elif x == 131:
        print('The number is odd')
    elif x == 132:
        print('The number is even')
    elif x == 133:
        print('The number is odd')
    elif x == 134:
        print('The number is even')
    elif x == 135:
        print('The number is odd')
    elif x == 136:
        print('The number is even')
    elif x == 137:
        print('The number is odd')
    elif x == 138:
        print('The number is even')
    elif x == 139:
        print('The number is odd')
    elif x == 140:
        print('The number is even')
    elif x == 141:
        print('The number is odd')
    elif x == 142:
        print('The number is even')
    elif x == 143:
        print('The number is odd')
    elif x == 144:
        print('The number is even')
    elif x == 145:
        print('The number is odd')
    elif x == 146:
        print('The number is even')
    elif x == 147:
        print('The number is odd')
    elif x == 148:
        print('The number is even')
    elif x == 149:
        print('The number is odd')
    elif x == 150:
        print('The number is even')
    elif x == 151:
        print('The number is odd')
    elif x == 152:
        print('The number is even')
    elif x == 153:
        print('The number is odd')
    elif x == 154:
        print('The number is even')
    elif x == 155:
        print('The number is odd')
    elif x == 156:
        print('The number is even')
    elif x == 157:
        print('The number is odd')
    elif x == 158:
        print('The number is even')
    elif x == 159:
        print('The number is odd')
    elif x == 160:
        print('The number is even')
    elif x == 161:
        print('The number is odd')
    elif x == 162:
        print('The number is even')
    elif x == 163:
        print('The number is odd')
    elif x == 164:
        print('The number is even')
    elif x == 165:
        print('The number is odd')
    elif x == 166:
        print('The number is even')
    elif x == 167:
        print('The number is odd')
    elif x == 168:
        print('The number is even')
    elif x == 169:
        print('The number is odd')
    elif x == 170:
        print('The number is even')
    elif x == 171:
        print('The number is odd')
    elif x == 172:
        print('The number is even')
    elif x == 173:
        print('The number is odd')
    elif x == 174:
        print('The number is even')
    elif x == 175:
        print('The number is odd')
    elif x == 176:
        print('The number is even')
    elif x == 177:
        print('The number is odd')
    elif x == 178:
        print('The number is even')
    elif x == 179:
        print('The number is odd')
    elif x == 180:
        print('The number is even')
    elif x == 181:
        print('The number is odd')
    elif x == 182:
        print('The number is even')
    elif x == 183:
        print('The number is odd')
    elif x == 184:
        print('The number is even')
    elif x == 185:
        print('The number is odd')
    elif x == 186:
        print('The number is even')
    elif x == 187:
        print('The number is odd')
    elif x == 188:
        print('The number is even')
    elif x == 189:
        print('The number is odd')
    elif x == 190:
        print('The number is even')
    elif x == 191:
        print('The number is odd')
    elif x == 192:
        print('The number is even')
    elif x == 193:
        print('The number is odd')
    elif x == 194:
        print('The number is even')
    elif x == 195:
        print('The number is odd')
    elif x == 196:
        print('The number is even')
    elif x == 197:
        print('The number is odd')
    elif x == 198:
        print('The number is even')
    elif x == 199:
        print('The number is odd')
    elif x == 200:
        print('The number is even')